# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from heron/IRSensors.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import heron.msg

class IRSensors(genpy.Message):
  _md5sum = "d2d4f6afdad29c06c7d455d83f2670d6"
  _type = "heron/IRSensors"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """ValueUnitFloat[4] av_gauche
ValueUnitFloat[4] av_droit
ValueUnitFloat[4] ar_gauche
ValueUnitFloat[4] ar_droit
ValueUnitFloat[4] ar

================================================================================
MSG: heron/ValueUnitFloat
float64 value
string unit
"""
  __slots__ = ['av_gauche','av_droit','ar_gauche','ar_droit','ar']
  _slot_types = ['heron/ValueUnitFloat[4]','heron/ValueUnitFloat[4]','heron/ValueUnitFloat[4]','heron/ValueUnitFloat[4]','heron/ValueUnitFloat[4]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       av_gauche,av_droit,ar_gauche,ar_droit,ar

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IRSensors, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.av_gauche is None:
        self.av_gauche = [heron.msg.ValueUnitFloat() for _ in range(4)]
      if self.av_droit is None:
        self.av_droit = [heron.msg.ValueUnitFloat() for _ in range(4)]
      if self.ar_gauche is None:
        self.ar_gauche = [heron.msg.ValueUnitFloat() for _ in range(4)]
      if self.ar_droit is None:
        self.ar_droit = [heron.msg.ValueUnitFloat() for _ in range(4)]
      if self.ar is None:
        self.ar = [heron.msg.ValueUnitFloat() for _ in range(4)]
    else:
      self.av_gauche = [heron.msg.ValueUnitFloat() for _ in range(4)]
      self.av_droit = [heron.msg.ValueUnitFloat() for _ in range(4)]
      self.ar_gauche = [heron.msg.ValueUnitFloat() for _ in range(4)]
      self.ar_droit = [heron.msg.ValueUnitFloat() for _ in range(4)]
      self.ar = [heron.msg.ValueUnitFloat() for _ in range(4)]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      if len(self.av_gauche) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.av_gauche), 'self.av_gauche')))
      for val1 in self.av_gauche:
        _x = val1.value
        buff.write(_get_struct_d().pack(_x))
        _x = val1.unit
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      if len(self.av_droit) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.av_droit), 'self.av_droit')))
      for val1 in self.av_droit:
        _x = val1.value
        buff.write(_get_struct_d().pack(_x))
        _x = val1.unit
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      if len(self.ar_gauche) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.ar_gauche), 'self.ar_gauche')))
      for val1 in self.ar_gauche:
        _x = val1.value
        buff.write(_get_struct_d().pack(_x))
        _x = val1.unit
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      if len(self.ar_droit) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.ar_droit), 'self.ar_droit')))
      for val1 in self.ar_droit:
        _x = val1.value
        buff.write(_get_struct_d().pack(_x))
        _x = val1.unit
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      if len(self.ar) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.ar), 'self.ar')))
      for val1 in self.ar:
        _x = val1.value
        buff.write(_get_struct_d().pack(_x))
        _x = val1.unit
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.av_gauche is None:
        self.av_gauche = None
      if self.av_droit is None:
        self.av_droit = None
      if self.ar_gauche is None:
        self.ar_gauche = None
      if self.ar_droit is None:
        self.ar_droit = None
      if self.ar is None:
        self.ar = None
      end = 0
      self.av_gauche = []
      for i in range(0, 4):
        val1 = heron.msg.ValueUnitFloat()
        start = end
        end += 8
        (val1.value,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.unit = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.unit = str[start:end]
        self.av_gauche.append(val1)
      self.av_droit = []
      for i in range(0, 4):
        val1 = heron.msg.ValueUnitFloat()
        start = end
        end += 8
        (val1.value,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.unit = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.unit = str[start:end]
        self.av_droit.append(val1)
      self.ar_gauche = []
      for i in range(0, 4):
        val1 = heron.msg.ValueUnitFloat()
        start = end
        end += 8
        (val1.value,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.unit = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.unit = str[start:end]
        self.ar_gauche.append(val1)
      self.ar_droit = []
      for i in range(0, 4):
        val1 = heron.msg.ValueUnitFloat()
        start = end
        end += 8
        (val1.value,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.unit = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.unit = str[start:end]
        self.ar_droit.append(val1)
      self.ar = []
      for i in range(0, 4):
        val1 = heron.msg.ValueUnitFloat()
        start = end
        end += 8
        (val1.value,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.unit = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.unit = str[start:end]
        self.ar.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      if len(self.av_gauche) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.av_gauche), 'self.av_gauche')))
      for val1 in self.av_gauche:
        _x = val1.value
        buff.write(_get_struct_d().pack(_x))
        _x = val1.unit
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      if len(self.av_droit) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.av_droit), 'self.av_droit')))
      for val1 in self.av_droit:
        _x = val1.value
        buff.write(_get_struct_d().pack(_x))
        _x = val1.unit
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      if len(self.ar_gauche) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.ar_gauche), 'self.ar_gauche')))
      for val1 in self.ar_gauche:
        _x = val1.value
        buff.write(_get_struct_d().pack(_x))
        _x = val1.unit
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      if len(self.ar_droit) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.ar_droit), 'self.ar_droit')))
      for val1 in self.ar_droit:
        _x = val1.value
        buff.write(_get_struct_d().pack(_x))
        _x = val1.unit
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      if len(self.ar) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.ar), 'self.ar')))
      for val1 in self.ar:
        _x = val1.value
        buff.write(_get_struct_d().pack(_x))
        _x = val1.unit
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.av_gauche is None:
        self.av_gauche = None
      if self.av_droit is None:
        self.av_droit = None
      if self.ar_gauche is None:
        self.ar_gauche = None
      if self.ar_droit is None:
        self.ar_droit = None
      if self.ar is None:
        self.ar = None
      end = 0
      self.av_gauche = []
      for i in range(0, 4):
        val1 = heron.msg.ValueUnitFloat()
        start = end
        end += 8
        (val1.value,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.unit = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.unit = str[start:end]
        self.av_gauche.append(val1)
      self.av_droit = []
      for i in range(0, 4):
        val1 = heron.msg.ValueUnitFloat()
        start = end
        end += 8
        (val1.value,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.unit = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.unit = str[start:end]
        self.av_droit.append(val1)
      self.ar_gauche = []
      for i in range(0, 4):
        val1 = heron.msg.ValueUnitFloat()
        start = end
        end += 8
        (val1.value,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.unit = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.unit = str[start:end]
        self.ar_gauche.append(val1)
      self.ar_droit = []
      for i in range(0, 4):
        val1 = heron.msg.ValueUnitFloat()
        start = end
        end += 8
        (val1.value,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.unit = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.unit = str[start:end]
        self.ar_droit.append(val1)
      self.ar = []
      for i in range(0, 4):
        val1 = heron.msg.ValueUnitFloat()
        start = end
        end += 8
        (val1.value,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.unit = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.unit = str[start:end]
        self.ar.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
