// Auto-generated. Do not edit!

// (in-package turtlebot2i_arm_director.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class NamedPoseDirectorGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.named_pose = null;
    }
    else {
      if (initObj.hasOwnProperty('named_pose')) {
        this.named_pose = initObj.named_pose
      }
      else {
        this.named_pose = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type NamedPoseDirectorGoal
    // Serialize message field [named_pose]
    bufferOffset = _serializer.string(obj.named_pose, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type NamedPoseDirectorGoal
    let len;
    let data = new NamedPoseDirectorGoal(null);
    // Deserialize message field [named_pose]
    data.named_pose = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.named_pose.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'turtlebot2i_arm_director/NamedPoseDirectorGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f1d8df4ffcc1d667593f4814a7cca462';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    string named_pose
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new NamedPoseDirectorGoal(null);
    if (msg.named_pose !== undefined) {
      resolved.named_pose = msg.named_pose;
    }
    else {
      resolved.named_pose = ''
    }

    return resolved;
    }
};

module.exports = NamedPoseDirectorGoal;
