// Generated by gencpp from file robotino_isen/AnnotatedPoseRequest.msg
// DO NOT EDIT!


#ifndef ROBOTINO_ISEN_MESSAGE_ANNOTATEDPOSEREQUEST_H
#define ROBOTINO_ISEN_MESSAGE_ANNOTATEDPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotino_isen/AnnotatedPoses.h>

namespace robotino_isen
{
template <class ContainerAllocator>
struct AnnotatedPoseRequest_
{
  typedef AnnotatedPoseRequest_<ContainerAllocator> Type;

  AnnotatedPoseRequest_()
    : annotatedPose()  {
    }
  AnnotatedPoseRequest_(const ContainerAllocator& _alloc)
    : annotatedPose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robotino_isen::AnnotatedPoses_<ContainerAllocator>  _annotatedPose_type;
  _annotatedPose_type annotatedPose;





  typedef boost::shared_ptr< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AnnotatedPoseRequest_

typedef ::robotino_isen::AnnotatedPoseRequest_<std::allocator<void> > AnnotatedPoseRequest;

typedef boost::shared_ptr< ::robotino_isen::AnnotatedPoseRequest > AnnotatedPoseRequestPtr;
typedef boost::shared_ptr< ::robotino_isen::AnnotatedPoseRequest const> AnnotatedPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotino_isen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'robotino_isen': ['/home/robotino/catkin_ws/src/robotino_isen/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d0ccfa12f5e09103ce667ff0b82b210";
  }

  static const char* value(const ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d0ccfa12f5e0910ULL;
  static const uint64_t static_value2 = 0x3ce667ff0b82b210ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotino_isen/AnnotatedPoseRequest";
  }

  static const char* value(const ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "AnnotatedPoses annotatedPose\n\
\n\
================================================================================\n\
MSG: robotino_isen/AnnotatedPoses\n\
string name\n\
geometry_msgs/Point pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.annotatedPose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnnotatedPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotino_isen::AnnotatedPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "annotatedPose: ";
    s << std::endl;
    Printer< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> >::stream(s, indent + "  ", v.annotatedPose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_ISEN_MESSAGE_ANNOTATEDPOSEREQUEST_H
