// Generated by gencpp from file robotino_isen/AnnotatedPose.msg
// DO NOT EDIT!


#ifndef ROBOTINO_ISEN_MESSAGE_ANNOTATEDPOSE_H
#define ROBOTINO_ISEN_MESSAGE_ANNOTATEDPOSE_H

#include <ros/service_traits.h>


#include <robotino_isen/AnnotatedPoseRequest.h>
#include <robotino_isen/AnnotatedPoseResponse.h>


namespace robotino_isen
{

struct AnnotatedPose
{

typedef AnnotatedPoseRequest Request;
typedef AnnotatedPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnnotatedPose
} // namespace robotino_isen


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotino_isen::AnnotatedPose > {
  static const char* value()
  {
    return "4d0ccfa12f5e09103ce667ff0b82b210";
  }

  static const char* value(const ::robotino_isen::AnnotatedPose&) { return value(); }
};

template<>
struct DataType< ::robotino_isen::AnnotatedPose > {
  static const char* value()
  {
    return "robotino_isen/AnnotatedPose";
  }

  static const char* value(const ::robotino_isen::AnnotatedPose&) { return value(); }
};


// service_traits::MD5Sum< ::robotino_isen::AnnotatedPoseRequest> should match 
// service_traits::MD5Sum< ::robotino_isen::AnnotatedPose > 
template<>
struct MD5Sum< ::robotino_isen::AnnotatedPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_isen::AnnotatedPose >::value();
  }
  static const char* value(const ::robotino_isen::AnnotatedPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_isen::AnnotatedPoseRequest> should match 
// service_traits::DataType< ::robotino_isen::AnnotatedPose > 
template<>
struct DataType< ::robotino_isen::AnnotatedPoseRequest>
{
  static const char* value()
  {
    return DataType< ::robotino_isen::AnnotatedPose >::value();
  }
  static const char* value(const ::robotino_isen::AnnotatedPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotino_isen::AnnotatedPoseResponse> should match 
// service_traits::MD5Sum< ::robotino_isen::AnnotatedPose > 
template<>
struct MD5Sum< ::robotino_isen::AnnotatedPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_isen::AnnotatedPose >::value();
  }
  static const char* value(const ::robotino_isen::AnnotatedPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_isen::AnnotatedPoseResponse> should match 
// service_traits::DataType< ::robotino_isen::AnnotatedPose > 
template<>
struct DataType< ::robotino_isen::AnnotatedPoseResponse>
{
  static const char* value()
  {
    return DataType< ::robotino_isen::AnnotatedPose >::value();
  }
  static const char* value(const ::robotino_isen::AnnotatedPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTINO_ISEN_MESSAGE_ANNOTATEDPOSE_H
