// Generated by gencpp from file robotino_isen/AnnotatedPoses.msg
// DO NOT EDIT!


#ifndef ROBOTINO_ISEN_MESSAGE_ANNOTATEDPOSES_H
#define ROBOTINO_ISEN_MESSAGE_ANNOTATEDPOSES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace robotino_isen
{
template <class ContainerAllocator>
struct AnnotatedPoses_
{
  typedef AnnotatedPoses_<ContainerAllocator> Type;

  AnnotatedPoses_()
    : name()
    , pose()  {
    }
  AnnotatedPoses_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> const> ConstPtr;

}; // struct AnnotatedPoses_

typedef ::robotino_isen::AnnotatedPoses_<std::allocator<void> > AnnotatedPoses;

typedef boost::shared_ptr< ::robotino_isen::AnnotatedPoses > AnnotatedPosesPtr;
typedef boost::shared_ptr< ::robotino_isen::AnnotatedPoses const> AnnotatedPosesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotino_isen::AnnotatedPoses_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotino_isen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'robotino_isen': ['/home/robotino/catkin_ws/src/robotino_isen/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75e825a453c409c5eb9493536e0300c0";
  }

  static const char* value(const ::robotino_isen::AnnotatedPoses_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75e825a453c409c5ULL;
  static const uint64_t static_value2 = 0xeb9493536e0300c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotino_isen/AnnotatedPoses";
  }

  static const char* value(const ::robotino_isen::AnnotatedPoses_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
geometry_msgs/Point pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::robotino_isen::AnnotatedPoses_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnnotatedPoses_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_isen::AnnotatedPoses_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotino_isen::AnnotatedPoses_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_ISEN_MESSAGE_ANNOTATEDPOSES_H
