// Generated by gencpp from file robotino_isen/AnnotatedPoseResponse.msg
// DO NOT EDIT!


#ifndef ROBOTINO_ISEN_MESSAGE_ANNOTATEDPOSERESPONSE_H
#define ROBOTINO_ISEN_MESSAGE_ANNOTATEDPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotino_isen
{
template <class ContainerAllocator>
struct AnnotatedPoseResponse_
{
  typedef AnnotatedPoseResponse_<ContainerAllocator> Type;

  AnnotatedPoseResponse_()
    {
    }
  AnnotatedPoseResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AnnotatedPoseResponse_

typedef ::robotino_isen::AnnotatedPoseResponse_<std::allocator<void> > AnnotatedPoseResponse;

typedef boost::shared_ptr< ::robotino_isen::AnnotatedPoseResponse > AnnotatedPoseResponsePtr;
typedef boost::shared_ptr< ::robotino_isen::AnnotatedPoseResponse const> AnnotatedPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotino_isen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'robotino_isen': ['/home/robotino/catkin_ws/src/robotino_isen/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotino_isen/AnnotatedPoseResponse";
  }

  static const char* value(const ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnnotatedPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robotino_isen::AnnotatedPoseResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_ISEN_MESSAGE_ANNOTATEDPOSERESPONSE_H
