use_dwa: true
max_trans_vel: 0.55
min_trans_vel: 0.1
max_vel_x: 0.55
min_vel_x: 0.0
max_vel_y: 0.1
min_vel_y: -0.1
max_rot_vel: 1.0
min_rot_vel: 0.4
xy_goal_tolerance: 0.1
yaw_goal_tolerance: 0.3
holonomic: true
controller_frequency: 20
sim_time: 4.0
vx_samples: 20
vy_samples: 0
vth_samples: 40
path_distance_bias: 32.0
goal_distance_bias: 20.0
occdist_scale: 0.02
forward_point_distance: 0.325
stop_time_buffer: 0.2
scaling_speed: 0.25
max_scaling_factor: 0.2
