local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  meter_scoring: true
  width: 4.0
  height: 4.0
  resolution: 0.02
  tranform_tolerance: 3.0
 
