// Generated by gencpp from file turtlebot2i_marker_manipulation/ToolDetectionGoal.msg
// DO NOT EDIT!


#ifndef TURTLEBOT2I_MARKER_MANIPULATION_MESSAGE_TOOLDETECTIONGOAL_H
#define TURTLEBOT2I_MARKER_MANIPULATION_MESSAGE_TOOLDETECTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot2i_marker_manipulation
{
template <class ContainerAllocator>
struct ToolDetectionGoal_
{
  typedef ToolDetectionGoal_<ContainerAllocator> Type;

  ToolDetectionGoal_()
    : frame()
    , table_height(0.0)
    , toolholder_size(0.0)  {
    }
  ToolDetectionGoal_(const ContainerAllocator& _alloc)
    : frame(_alloc)
    , table_height(0.0)
    , toolholder_size(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_type;
  _frame_type frame;

   typedef float _table_height_type;
  _table_height_type table_height;

   typedef float _toolholder_size_type;
  _toolholder_size_type toolholder_size;





  typedef boost::shared_ptr< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ToolDetectionGoal_

typedef ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<std::allocator<void> > ToolDetectionGoal;

typedef boost::shared_ptr< ::turtlebot2i_marker_manipulation::ToolDetectionGoal > ToolDetectionGoalPtr;
typedef boost::shared_ptr< ::turtlebot2i_marker_manipulation::ToolDetectionGoal const> ToolDetectionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlebot2i_marker_manipulation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'turtlebot2i_marker_manipulation': ['/home/turtlebot/turtlebot2i/src/turtlebot2i_apps/turtlebot2i_marker_manipulation/msg', '/home/turtlebot/turtlebot2i/devel/share/turtlebot2i_marker_manipulation/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6cf80dffa24f7575114caac8108f08af";
  }

  static const char* value(const ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6cf80dffa24f7575ULL;
  static const uint64_t static_value2 = 0x114caac8108f08afULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot2i_marker_manipulation/ToolDetectionGoal";
  }

  static const char* value(const ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
string frame\n\
float32 table_height\n\
float32 toolholder_size\n\
";
  }

  static const char* value(const ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
      stream.next(m.table_height);
      stream.next(m.toolholder_size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToolDetectionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot2i_marker_manipulation::ToolDetectionGoal_<ContainerAllocator>& v)
  {
    s << indent << "frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame);
    s << indent << "table_height: ";
    Printer<float>::stream(s, indent + "  ", v.table_height);
    s << indent << "toolholder_size: ";
    Printer<float>::stream(s, indent + "  ", v.toolholder_size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT2I_MARKER_MANIPULATION_MESSAGE_TOOLDETECTIONGOAL_H
