// Generated by gencpp from file turtlebot2i_arm_director/NamedPoseDirectorGoal.msg
// DO NOT EDIT!


#ifndef TURTLEBOT2I_ARM_DIRECTOR_MESSAGE_NAMEDPOSEDIRECTORGOAL_H
#define TURTLEBOT2I_ARM_DIRECTOR_MESSAGE_NAMEDPOSEDIRECTORGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot2i_arm_director
{
template <class ContainerAllocator>
struct NamedPoseDirectorGoal_
{
  typedef NamedPoseDirectorGoal_<ContainerAllocator> Type;

  NamedPoseDirectorGoal_()
    : named_pose()  {
    }
  NamedPoseDirectorGoal_(const ContainerAllocator& _alloc)
    : named_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _named_pose_type;
  _named_pose_type named_pose;





  typedef boost::shared_ptr< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NamedPoseDirectorGoal_

typedef ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<std::allocator<void> > NamedPoseDirectorGoal;

typedef boost::shared_ptr< ::turtlebot2i_arm_director::NamedPoseDirectorGoal > NamedPoseDirectorGoalPtr;
typedef boost::shared_ptr< ::turtlebot2i_arm_director::NamedPoseDirectorGoal const> NamedPoseDirectorGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlebot2i_arm_director

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'turtlebot2i_arm_director': ['/home/turtlebot/turtlebot2i/devel/share/turtlebot2i_arm_director/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1d8df4ffcc1d667593f4814a7cca462";
  }

  static const char* value(const ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1d8df4ffcc1d667ULL;
  static const uint64_t static_value2 = 0x593f4814a7cca462ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot2i_arm_director/NamedPoseDirectorGoal";
  }

  static const char* value(const ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
string named_pose\n\
";
  }

  static const char* value(const ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.named_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NamedPoseDirectorGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot2i_arm_director::NamedPoseDirectorGoal_<ContainerAllocator>& v)
  {
    s << indent << "named_pose: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.named_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT2I_ARM_DIRECTOR_MESSAGE_NAMEDPOSEDIRECTORGOAL_H
