// Generated by gencpp from file turtlebot_isen_msgs/BatteryState.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_ISEN_MSGS_MESSAGE_BATTERYSTATE_H
#define TURTLEBOT_ISEN_MSGS_MESSAGE_BATTERYSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot_isen_msgs
{
template <class ContainerAllocator>
struct BatteryState_
{
  typedef BatteryState_<ContainerAllocator> Type;

  BatteryState_()
    : Charger()
    , Battery(0.0)  {
    }
  BatteryState_(const ContainerAllocator& _alloc)
    : Charger(_alloc)
    , Battery(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Charger_type;
  _Charger_type Charger;

   typedef float _Battery_type;
  _Battery_type Battery;





  typedef boost::shared_ptr< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> const> ConstPtr;

}; // struct BatteryState_

typedef ::turtlebot_isen_msgs::BatteryState_<std::allocator<void> > BatteryState;

typedef boost::shared_ptr< ::turtlebot_isen_msgs::BatteryState > BatteryStatePtr;
typedef boost::shared_ptr< ::turtlebot_isen_msgs::BatteryState const> BatteryStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlebot_isen_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'turtlebot_isen_msgs': ['/home/turtlebot/turtlebot2i/src/turtlebot_isen_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d9e281ba46539ec900610c49fadf3ce";
  }

  static const char* value(const ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d9e281ba46539ecULL;
  static const uint64_t static_value2 = 0x900610c49fadf3ceULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_isen_msgs/BatteryState";
  }

  static const char* value(const ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string Charger\n\
\n\
float32 Battery\n\
";
  }

  static const char* value(const ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Charger);
      stream.next(m.Battery);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BatteryState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_isen_msgs::BatteryState_<ContainerAllocator>& v)
  {
    s << indent << "Charger: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Charger);
    s << indent << "Battery: ";
    Printer<float>::stream(s, indent + "  ", v.Battery);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_ISEN_MSGS_MESSAGE_BATTERYSTATE_H
