// Generated by gencpp from file heron/Encoders.msg
// DO NOT EDIT!


#ifndef HERON_MESSAGE_ENCODERS_H
#define HERON_MESSAGE_ENCODERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heron
{
template <class ContainerAllocator>
struct Encoders_
{
  typedef Encoders_<ContainerAllocator> Type;

  Encoders_()
    : EncFl(0)
    , EncFr(0)
    , EncBl(0)
    , EncBr(0)  {
    }
  Encoders_(const ContainerAllocator& _alloc)
    : EncFl(0)
    , EncFr(0)
    , EncBl(0)
    , EncBr(0)  {
  (void)_alloc;
    }



   typedef int64_t _EncFl_type;
  _EncFl_type EncFl;

   typedef int64_t _EncFr_type;
  _EncFr_type EncFr;

   typedef int64_t _EncBl_type;
  _EncBl_type EncBl;

   typedef int64_t _EncBr_type;
  _EncBr_type EncBr;





  typedef boost::shared_ptr< ::heron::Encoders_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heron::Encoders_<ContainerAllocator> const> ConstPtr;

}; // struct Encoders_

typedef ::heron::Encoders_<std::allocator<void> > Encoders;

typedef boost::shared_ptr< ::heron::Encoders > EncodersPtr;
typedef boost::shared_ptr< ::heron::Encoders const> EncodersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heron::Encoders_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heron::Encoders_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace heron

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'heron': ['/home/nvidia/catkin2_ws/src/heron_software/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::heron::Encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heron::Encoders_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heron::Encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heron::Encoders_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heron::Encoders_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heron::Encoders_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heron::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c892101147370a467da7bacfd2db99e";
  }

  static const char* value(const ::heron::Encoders_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c892101147370a4ULL;
  static const uint64_t static_value2 = 0x67da7bacfd2db99eULL;
};

template<class ContainerAllocator>
struct DataType< ::heron::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heron/Encoders";
  }

  static const char* value(const ::heron::Encoders_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heron::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 EncFl\n\
int64 EncFr\n\
int64 EncBl\n\
int64 EncBr\n\
";
  }

  static const char* value(const ::heron::Encoders_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heron::Encoders_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.EncFl);
      stream.next(m.EncFr);
      stream.next(m.EncBl);
      stream.next(m.EncBr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoders_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heron::Encoders_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heron::Encoders_<ContainerAllocator>& v)
  {
    s << indent << "EncFl: ";
    Printer<int64_t>::stream(s, indent + "  ", v.EncFl);
    s << indent << "EncFr: ";
    Printer<int64_t>::stream(s, indent + "  ", v.EncFr);
    s << indent << "EncBl: ";
    Printer<int64_t>::stream(s, indent + "  ", v.EncBl);
    s << indent << "EncBr: ";
    Printer<int64_t>::stream(s, indent + "  ", v.EncBr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERON_MESSAGE_ENCODERS_H
