// Generated by gencpp from file heron/USIRSensors.msg
// DO NOT EDIT!


#ifndef HERON_MESSAGE_USIRSENSORS_H
#define HERON_MESSAGE_USIRSENSORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <heron/ValueUnitFloat.h>
#include <heron/ValueUnitFloat.h>

namespace heron
{
template <class ContainerAllocator>
struct USIRSensors_
{
  typedef USIRSensors_<ContainerAllocator> Type;

  USIRSensors_()
    : gauche()
    , droit()  {
    }
  USIRSensors_(const ContainerAllocator& _alloc)
    : gauche()
    , droit()  {
  (void)_alloc;
      gauche.assign( ::heron::ValueUnitFloat_<ContainerAllocator> (_alloc));

      droit.assign( ::heron::ValueUnitFloat_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::heron::ValueUnitFloat_<ContainerAllocator> , 4>  _gauche_type;
  _gauche_type gauche;

   typedef boost::array< ::heron::ValueUnitFloat_<ContainerAllocator> , 4>  _droit_type;
  _droit_type droit;





  typedef boost::shared_ptr< ::heron::USIRSensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heron::USIRSensors_<ContainerAllocator> const> ConstPtr;

}; // struct USIRSensors_

typedef ::heron::USIRSensors_<std::allocator<void> > USIRSensors;

typedef boost::shared_ptr< ::heron::USIRSensors > USIRSensorsPtr;
typedef boost::shared_ptr< ::heron::USIRSensors const> USIRSensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heron::USIRSensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heron::USIRSensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace heron

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'heron': ['/home/nvidia/catkin2_ws/src/heron_software/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::heron::USIRSensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heron::USIRSensors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heron::USIRSensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heron::USIRSensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heron::USIRSensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heron::USIRSensors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heron::USIRSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec3639fb43a99ba8f34b5269205642b7";
  }

  static const char* value(const ::heron::USIRSensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec3639fb43a99ba8ULL;
  static const uint64_t static_value2 = 0xf34b5269205642b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::heron::USIRSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heron/USIRSensors";
  }

  static const char* value(const ::heron::USIRSensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heron::USIRSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ValueUnitFloat[4] gauche\n\
ValueUnitFloat[4] droit\n\
\n\
================================================================================\n\
MSG: heron/ValueUnitFloat\n\
float64 value\n\
string unit\n\
";
  }

  static const char* value(const ::heron::USIRSensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heron::USIRSensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gauche);
      stream.next(m.droit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct USIRSensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heron::USIRSensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heron::USIRSensors_<ContainerAllocator>& v)
  {
    s << indent << "gauche[]" << std::endl;
    for (size_t i = 0; i < v.gauche.size(); ++i)
    {
      s << indent << "  gauche[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::heron::ValueUnitFloat_<ContainerAllocator> >::stream(s, indent + "    ", v.gauche[i]);
    }
    s << indent << "droit[]" << std::endl;
    for (size_t i = 0; i < v.droit.size(); ++i)
    {
      s << indent << "  droit[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::heron::ValueUnitFloat_<ContainerAllocator> >::stream(s, indent + "    ", v.droit[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERON_MESSAGE_USIRSENSORS_H
