// Generated by gencpp from file heron/winch.msg
// DO NOT EDIT!


#ifndef HERON_MESSAGE_WINCH_H
#define HERON_MESSAGE_WINCH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heron
{
template <class ContainerAllocator>
struct winch_
{
  typedef winch_<ContainerAllocator> Type;

  winch_()
    : height(0.0)
    , heightTicks(0.0)  {
    }
  winch_(const ContainerAllocator& _alloc)
    : height(0.0)
    , heightTicks(0.0)  {
  (void)_alloc;
    }



   typedef float _height_type;
  _height_type height;

   typedef float _heightTicks_type;
  _heightTicks_type heightTicks;





  typedef boost::shared_ptr< ::heron::winch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heron::winch_<ContainerAllocator> const> ConstPtr;

}; // struct winch_

typedef ::heron::winch_<std::allocator<void> > winch;

typedef boost::shared_ptr< ::heron::winch > winchPtr;
typedef boost::shared_ptr< ::heron::winch const> winchConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heron::winch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heron::winch_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace heron

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'heron': ['/home/nvidia/catkin2_ws/src/heron_software/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::heron::winch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heron::winch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heron::winch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heron::winch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heron::winch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heron::winch_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heron::winch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c1d8d82efdc45aeff9d8a7722fdb8ca";
  }

  static const char* value(const ::heron::winch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c1d8d82efdc45aeULL;
  static const uint64_t static_value2 = 0xff9d8a7722fdb8caULL;
};

template<class ContainerAllocator>
struct DataType< ::heron::winch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heron/winch";
  }

  static const char* value(const ::heron::winch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heron::winch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 height\n\
float32 heightTicks\n\
";
  }

  static const char* value(const ::heron::winch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heron::winch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
      stream.next(m.heightTicks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct winch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heron::winch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heron::winch_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "heightTicks: ";
    Printer<float>::stream(s, indent + "  ", v.heightTicks);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERON_MESSAGE_WINCH_H
