; Auto-generated. Do not edit!


(cl:in-package turtlebot2i_marker_manipulation-msg)


;//! \htmlinclude PickAndDrawFeedback.msg.html

(cl:defclass <PickAndDrawFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PickAndDrawFeedback (<PickAndDrawFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PickAndDrawFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PickAndDrawFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot2i_marker_manipulation-msg:<PickAndDrawFeedback> is deprecated: use turtlebot2i_marker_manipulation-msg:PickAndDrawFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PickAndDrawFeedback>) ostream)
  "Serializes a message object of type '<PickAndDrawFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PickAndDrawFeedback>) istream)
  "Deserializes a message object of type '<PickAndDrawFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PickAndDrawFeedback>)))
  "Returns string type for a message object of type '<PickAndDrawFeedback>"
  "turtlebot2i_marker_manipulation/PickAndDrawFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PickAndDrawFeedback)))
  "Returns string type for a message object of type 'PickAndDrawFeedback"
  "turtlebot2i_marker_manipulation/PickAndDrawFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PickAndDrawFeedback>)))
  "Returns md5sum for a message object of type '<PickAndDrawFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PickAndDrawFeedback)))
  "Returns md5sum for a message object of type 'PickAndDrawFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PickAndDrawFeedback>)))
  "Returns full string definition for message of type '<PickAndDrawFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PickAndDrawFeedback)))
  "Returns full string definition for message of type 'PickAndDrawFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PickAndDrawFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PickAndDrawFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PickAndDrawFeedback
))
