; Auto-generated. Do not edit!


(cl:in-package turtlebot2i_marker_manipulation-msg)


;//! \htmlinclude PickAndDrawResult.msg.html

(cl:defclass <PickAndDrawResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PickAndDrawResult (<PickAndDrawResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PickAndDrawResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PickAndDrawResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot2i_marker_manipulation-msg:<PickAndDrawResult> is deprecated: use turtlebot2i_marker_manipulation-msg:PickAndDrawResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PickAndDrawResult>) ostream)
  "Serializes a message object of type '<PickAndDrawResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PickAndDrawResult>) istream)
  "Deserializes a message object of type '<PickAndDrawResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PickAndDrawResult>)))
  "Returns string type for a message object of type '<PickAndDrawResult>"
  "turtlebot2i_marker_manipulation/PickAndDrawResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PickAndDrawResult)))
  "Returns string type for a message object of type 'PickAndDrawResult"
  "turtlebot2i_marker_manipulation/PickAndDrawResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PickAndDrawResult>)))
  "Returns md5sum for a message object of type '<PickAndDrawResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PickAndDrawResult)))
  "Returns md5sum for a message object of type 'PickAndDrawResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PickAndDrawResult>)))
  "Returns full string definition for message of type '<PickAndDrawResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PickAndDrawResult)))
  "Returns full string definition for message of type 'PickAndDrawResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PickAndDrawResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PickAndDrawResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PickAndDrawResult
))
