; Auto-generated. Do not edit!


(cl:in-package turtlebot2i_marker_manipulation-msg)


;//! \htmlinclude ToolDetectionFeedback.msg.html

(cl:defclass <ToolDetectionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ToolDetectionFeedback (<ToolDetectionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ToolDetectionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ToolDetectionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot2i_marker_manipulation-msg:<ToolDetectionFeedback> is deprecated: use turtlebot2i_marker_manipulation-msg:ToolDetectionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ToolDetectionFeedback>) ostream)
  "Serializes a message object of type '<ToolDetectionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ToolDetectionFeedback>) istream)
  "Deserializes a message object of type '<ToolDetectionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ToolDetectionFeedback>)))
  "Returns string type for a message object of type '<ToolDetectionFeedback>"
  "turtlebot2i_marker_manipulation/ToolDetectionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ToolDetectionFeedback)))
  "Returns string type for a message object of type 'ToolDetectionFeedback"
  "turtlebot2i_marker_manipulation/ToolDetectionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ToolDetectionFeedback>)))
  "Returns md5sum for a message object of type '<ToolDetectionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ToolDetectionFeedback)))
  "Returns md5sum for a message object of type 'ToolDetectionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ToolDetectionFeedback>)))
  "Returns full string definition for message of type '<ToolDetectionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ToolDetectionFeedback)))
  "Returns full string definition for message of type 'ToolDetectionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ToolDetectionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ToolDetectionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ToolDetectionFeedback
))
