(cl:defpackage turtlebot2i_arm_director-msg
  (:use )
  (:export
   "<NAMEDPOSEDIRECTORACTION>"
   "NAMEDPOSEDIRECTORACTION"
   "<NAMEDPOSEDIRECTORACTIONFEEDBACK>"
   "NAMEDPOSEDIRECTORACTIONFEEDBACK"
   "<NAMEDPOSEDIRECTORACTIONGOAL>"
   "NAMEDPOSEDIRECTORACTIONGOAL"
   "<NAMEDPOSEDIRECTORACTIONRESULT>"
   "NAMEDPOSEDIRECTORACTIONRESULT"
   "<NAMEDPOSEDIRECTORFEEDBACK>"
   "NAMEDPOSEDIRECTORFEEDBACK"
   "<NAMEDPOSEDIRECTORGOAL>"
   "NAMEDPOSEDIRECTORGOAL"
   "<NAMEDPOSEDIRECTORRESULT>"
   "NAMEDPOSEDIRECTORRESULT"
  ))

