; Auto-generated. Do not edit!


(cl:in-package turtlebot2i_arm_director-msg)


;//! \htmlinclude NamedPoseDirectorFeedback.msg.html

(cl:defclass <NamedPoseDirectorFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass NamedPoseDirectorFeedback (<NamedPoseDirectorFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NamedPoseDirectorFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NamedPoseDirectorFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot2i_arm_director-msg:<NamedPoseDirectorFeedback> is deprecated: use turtlebot2i_arm_director-msg:NamedPoseDirectorFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NamedPoseDirectorFeedback>) ostream)
  "Serializes a message object of type '<NamedPoseDirectorFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NamedPoseDirectorFeedback>) istream)
  "Deserializes a message object of type '<NamedPoseDirectorFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NamedPoseDirectorFeedback>)))
  "Returns string type for a message object of type '<NamedPoseDirectorFeedback>"
  "turtlebot2i_arm_director/NamedPoseDirectorFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NamedPoseDirectorFeedback)))
  "Returns string type for a message object of type 'NamedPoseDirectorFeedback"
  "turtlebot2i_arm_director/NamedPoseDirectorFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NamedPoseDirectorFeedback>)))
  "Returns md5sum for a message object of type '<NamedPoseDirectorFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NamedPoseDirectorFeedback)))
  "Returns md5sum for a message object of type 'NamedPoseDirectorFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NamedPoseDirectorFeedback>)))
  "Returns full string definition for message of type '<NamedPoseDirectorFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NamedPoseDirectorFeedback)))
  "Returns full string definition for message of type 'NamedPoseDirectorFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NamedPoseDirectorFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NamedPoseDirectorFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'NamedPoseDirectorFeedback
))
