; Auto-generated. Do not edit!


(cl:in-package turtlebot2i_arm_director-msg)


;//! \htmlinclude NamedPoseDirectorResult.msg.html

(cl:defclass <NamedPoseDirectorResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass NamedPoseDirectorResult (<NamedPoseDirectorResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NamedPoseDirectorResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NamedPoseDirectorResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot2i_arm_director-msg:<NamedPoseDirectorResult> is deprecated: use turtlebot2i_arm_director-msg:NamedPoseDirectorResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NamedPoseDirectorResult>) ostream)
  "Serializes a message object of type '<NamedPoseDirectorResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NamedPoseDirectorResult>) istream)
  "Deserializes a message object of type '<NamedPoseDirectorResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NamedPoseDirectorResult>)))
  "Returns string type for a message object of type '<NamedPoseDirectorResult>"
  "turtlebot2i_arm_director/NamedPoseDirectorResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NamedPoseDirectorResult)))
  "Returns string type for a message object of type 'NamedPoseDirectorResult"
  "turtlebot2i_arm_director/NamedPoseDirectorResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NamedPoseDirectorResult>)))
  "Returns md5sum for a message object of type '<NamedPoseDirectorResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NamedPoseDirectorResult)))
  "Returns md5sum for a message object of type 'NamedPoseDirectorResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NamedPoseDirectorResult>)))
  "Returns full string definition for message of type '<NamedPoseDirectorResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NamedPoseDirectorResult)))
  "Returns full string definition for message of type 'NamedPoseDirectorResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NamedPoseDirectorResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NamedPoseDirectorResult>))
  "Converts a ROS message object to a list"
  (cl:list 'NamedPoseDirectorResult
))
