; Auto-generated. Do not edit!


(cl:in-package turtlebot2i_arm_director-msg)


;//! \htmlinclude NamedPoseDirectorGoal.msg.html

(cl:defclass <NamedPoseDirectorGoal> (roslisp-msg-protocol:ros-message)
  ((named_pose
    :reader named_pose
    :initarg :named_pose
    :type cl:string
    :initform ""))
)

(cl:defclass NamedPoseDirectorGoal (<NamedPoseDirectorGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NamedPoseDirectorGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NamedPoseDirectorGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot2i_arm_director-msg:<NamedPoseDirectorGoal> is deprecated: use turtlebot2i_arm_director-msg:NamedPoseDirectorGoal instead.")))

(cl:ensure-generic-function 'named_pose-val :lambda-list '(m))
(cl:defmethod named_pose-val ((m <NamedPoseDirectorGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader turtlebot2i_arm_director-msg:named_pose-val is deprecated.  Use turtlebot2i_arm_director-msg:named_pose instead.")
  (named_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NamedPoseDirectorGoal>) ostream)
  "Serializes a message object of type '<NamedPoseDirectorGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'named_pose))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'named_pose))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NamedPoseDirectorGoal>) istream)
  "Deserializes a message object of type '<NamedPoseDirectorGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'named_pose) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'named_pose) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NamedPoseDirectorGoal>)))
  "Returns string type for a message object of type '<NamedPoseDirectorGoal>"
  "turtlebot2i_arm_director/NamedPoseDirectorGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NamedPoseDirectorGoal)))
  "Returns string type for a message object of type 'NamedPoseDirectorGoal"
  "turtlebot2i_arm_director/NamedPoseDirectorGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NamedPoseDirectorGoal>)))
  "Returns md5sum for a message object of type '<NamedPoseDirectorGoal>"
  "f1d8df4ffcc1d667593f4814a7cca462")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NamedPoseDirectorGoal)))
  "Returns md5sum for a message object of type 'NamedPoseDirectorGoal"
  "f1d8df4ffcc1d667593f4814a7cca462")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NamedPoseDirectorGoal>)))
  "Returns full string definition for message of type '<NamedPoseDirectorGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string named_pose~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NamedPoseDirectorGoal)))
  "Returns full string definition for message of type 'NamedPoseDirectorGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string named_pose~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NamedPoseDirectorGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'named_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NamedPoseDirectorGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'NamedPoseDirectorGoal
    (cl:cons ':named_pose (named_pose msg))
))
