(cl:defpackage robotino_msgs-srv
  (:use )
  (:export
   "RESETODOMETRY"
   "<RESETODOMETRY-REQUEST>"
   "RESETODOMETRY-REQUEST"
   "<RESETODOMETRY-RESPONSE>"
   "RESETODOMETRY-RESPONSE"
   "SETENCODERPOSITION"
   "<SETENCODERPOSITION-REQUEST>"
   "SETENCODERPOSITION-REQUEST"
   "<SETENCODERPOSITION-RESPONSE>"
   "SETENCODERPOSITION-RESPONSE"
   "SETFOLLOWSTATE"
   "<SETFOLLOWSTATE-REQUEST>"
   "SETFOLLOWSTATE-REQUEST"
   "<SETFOLLOWSTATE-RESPONSE>"
   "SETFOLLOWSTATE-RESPONSE"
   "SETGRIPPERSTATE"
   "<SETGRIPPERSTATE-REQUEST>"
   "SETGRIPPERSTATE-REQUEST"
   "<SETGRIPPERSTATE-RESPONSE>"
   "SETGRIPPERSTATE-RESPONSE"
  ))

