// Generated by gencpp from file robotino_msgs/SetFollowState.msg
// DO NOT EDIT!


#ifndef ROBOTINO_MSGS_MESSAGE_SETFOLLOWSTATE_H
#define ROBOTINO_MSGS_MESSAGE_SETFOLLOWSTATE_H

#include <ros/service_traits.h>


#include <robotino_msgs/SetFollowStateRequest.h>
#include <robotino_msgs/SetFollowStateResponse.h>


namespace robotino_msgs
{

struct SetFollowState
{

typedef SetFollowStateRequest Request;
typedef SetFollowStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFollowState
} // namespace robotino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotino_msgs::SetFollowState > {
  static const char* value()
  {
    return "6095eaec0ed61c547340fdc2200c8372";
  }

  static const char* value(const ::robotino_msgs::SetFollowState&) { return value(); }
};

template<>
struct DataType< ::robotino_msgs::SetFollowState > {
  static const char* value()
  {
    return "robotino_msgs/SetFollowState";
  }

  static const char* value(const ::robotino_msgs::SetFollowState&) { return value(); }
};


// service_traits::MD5Sum< ::robotino_msgs::SetFollowStateRequest> should match 
// service_traits::MD5Sum< ::robotino_msgs::SetFollowState > 
template<>
struct MD5Sum< ::robotino_msgs::SetFollowStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_msgs::SetFollowState >::value();
  }
  static const char* value(const ::robotino_msgs::SetFollowStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_msgs::SetFollowStateRequest> should match 
// service_traits::DataType< ::robotino_msgs::SetFollowState > 
template<>
struct DataType< ::robotino_msgs::SetFollowStateRequest>
{
  static const char* value()
  {
    return DataType< ::robotino_msgs::SetFollowState >::value();
  }
  static const char* value(const ::robotino_msgs::SetFollowStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotino_msgs::SetFollowStateResponse> should match 
// service_traits::MD5Sum< ::robotino_msgs::SetFollowState > 
template<>
struct MD5Sum< ::robotino_msgs::SetFollowStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_msgs::SetFollowState >::value();
  }
  static const char* value(const ::robotino_msgs::SetFollowStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_msgs::SetFollowStateResponse> should match 
// service_traits::DataType< ::robotino_msgs::SetFollowState > 
template<>
struct DataType< ::robotino_msgs::SetFollowStateResponse>
{
  static const char* value()
  {
    return DataType< ::robotino_msgs::SetFollowState >::value();
  }
  static const char* value(const ::robotino_msgs::SetFollowStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTINO_MSGS_MESSAGE_SETFOLLOWSTATE_H
