inflation_layer:
  enabled: true
  cost_scaling_factor: 0.01
  inflation_radius: 0.15

global_costmap:
  enabled: true
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true
  resolution: 0.04
  transform_tolerance: 5.0

